# Generated by Django 4.2 on 2024-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="location",
            name="vehicle",
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
