version: "3.10"

services:
  app:
    restart: always
    build: .
    volumes:
      - .:/vehicle_tracking
    ports:
      - "8000:8000"
    image: app:vehicle_tracking
    container_name: iett_vehicle_tracking
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
