# Generated by Django 4.2 on 2024-09-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("license_number", models.CharField(max_length=20, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="driver", to="user.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
