# Generated by Django 4.2 on 2024-09-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("license_number", models.CharField(max_length=20, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
