# Generated by Django 4.2 on 2024-09-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("license_plate", models.CharField(max_length=10, unique=True)),
                ("model", models.CharField(blank=True, max_length=50, null=True)),
                ("make", models.CharField(blank=True, max_length=50, null=True)),
                ("year", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vehicles", to="driver.driver"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
