# Generated by Django 4.2 on 2024-09-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
        ("location", "0003_remove_location_timestamp_remove_location_vehicle_and_more"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="vehicles", to="driver.driver"
            ),
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="location",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="location",
            field=models.ManyToManyField(related_name="vehicles", to="location.location"),
        ),
    ]
