# Generated by Django 4.2 on 2024-09-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_alter_vehicle_driver_remove_vehicle_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="location",
            new_name="locations",
        ),
    ]
