# Generated by Django 4.2 on 2024-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_rename_location_vehicle_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
