# Generated by Django 4.2 on 2024-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("name", models.CharField(max_length=255)),
                ("personal_id", models.CharField(max_length=11, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
